# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{puavo-themes}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jouni Korhonen"]
  s.date = %q{2012-01-14}
  s.description = %q{Rails 3 engine for Puavo theme assets}
  s.email = %q{puavo@opinsys.fi}
  s.files = [
    "Rakefile",
    "VERSION",
    "lib/puavo-themes.rb",
    "lib/puavo-themes/rails/engine.rb",
    "puavo-themes.gemspec",
    "robots.txt",
    "vendor/assets/images/ajax-loader.gif",
    "vendor/assets/images/anonymous.png",
    "vendor/assets/images/bg-fabric-01.png",
    "vendor/assets/images/bg-fabric-02.png",
    "vendor/assets/images/bg-fabric-green-metal.png",
    "vendor/assets/images/bg-fabric-orange-metal.png",
    "vendor/assets/images/favicon.png",
    "vendor/assets/images/iconset-breathe.png",
    "vendor/assets/images/iconset.png",
    "vendor/assets/images/magnifier.png",
    "vendor/assets/images/rails.png",
    "vendor/assets/images/school.png",
    "vendor/assets/images/show-more.png",
    "vendor/assets/images/tools40.png",
    "vendor/assets/javascripts/application.js",
    "vendor/assets/javascripts/flot/excanvas.js",
    "vendor/assets/javascripts/flot/excanvas.min.js",
    "vendor/assets/javascripts/flot/jquery.colorhelpers.js",
    "vendor/assets/javascripts/flot/jquery.colorhelpers.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.crosshair.js",
    "vendor/assets/javascripts/flot/jquery.flot.crosshair.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.image.js",
    "vendor/assets/javascripts/flot/jquery.flot.image.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.js",
    "vendor/assets/javascripts/flot/jquery.flot.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.navigate.js",
    "vendor/assets/javascripts/flot/jquery.flot.navigate.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.selection.js",
    "vendor/assets/javascripts/flot/jquery.flot.selection.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.stack.js",
    "vendor/assets/javascripts/flot/jquery.flot.stack.min.js",
    "vendor/assets/javascripts/flot/jquery.flot.threshold.js",
    "vendor/assets/javascripts/flot/jquery.flot.threshold.min.js",
    "vendor/assets/javascripts/flot/jquery.js",
    "vendor/assets/javascripts/flot/jquery.min.js",
    "vendor/assets/javascripts/jquery-1.4.2.min.js",
    "vendor/assets/javascripts/jquery.jeditable.js",
    "vendor/assets/javascripts/jquery.jeditable.mini.js",
    "vendor/assets/javascripts/jquery.liveSearch.js",
    "vendor/assets/javascripts/jquery.textarea.js",
    "vendor/assets/javascripts/jquery.tooltip.js",
    "vendor/assets/javascripts/jquery.tooltip.min.js",
    "vendor/assets/javascripts/modernizr.custom.js",
    "vendor/assets/javascripts/organisations/edit.js",
    "vendor/assets/javascripts/password.js",
    "vendor/assets/javascripts/protofish-min.js",
    "vendor/assets/javascripts/protofish.js",
    "vendor/assets/javascripts/rails.js",
    "vendor/assets/javascripts/sun_olive.js",
    "vendor/assets/javascripts/users/import/new.js",
    "vendor/assets/javascripts/users/import/preview.js",
    "vendor/assets/stylesheets/army/kilohaili-protofish.css",
    "vendor/assets/stylesheets/army/kilohaili.css",
    "vendor/assets/stylesheets/army/navmenu.css",
    "vendor/assets/stylesheets/army/print.css",
    "vendor/assets/stylesheets/army/screen.css",
    "vendor/assets/stylesheets/blue/kilohaili-protofish.css",
    "vendor/assets/stylesheets/blue/kilohaili.css",
    "vendor/assets/stylesheets/blue/navmenu.css",
    "vendor/assets/stylesheets/blue/print.css",
    "vendor/assets/stylesheets/blue/screen.css",
    "vendor/assets/stylesheets/blueprint/ie.css",
    "vendor/assets/stylesheets/blueprint/plugins/buttons/icons/cross.png",
    "vendor/assets/stylesheets/blueprint/plugins/buttons/icons/key.png",
    "vendor/assets/stylesheets/blueprint/plugins/buttons/icons/tick.png",
    "vendor/assets/stylesheets/blueprint/plugins/buttons/readme.txt",
    "vendor/assets/stylesheets/blueprint/plugins/buttons/screen.css",
    "vendor/assets/stylesheets/blueprint/plugins/fancy-type/readme.txt",
    "vendor/assets/stylesheets/blueprint/plugins/fancy-type/screen.css",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/doc.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/email.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/external.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/feed.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/im.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/pdf.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/visited.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/icons/xls.png",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/readme.txt",
    "vendor/assets/stylesheets/blueprint/plugins/link-icons/screen.css",
    "vendor/assets/stylesheets/blueprint/plugins/rtl/readme.txt",
    "vendor/assets/stylesheets/blueprint/plugins/rtl/screen.css",
    "vendor/assets/stylesheets/blueprint/print.css",
    "vendor/assets/stylesheets/blueprint/screen.css",
    "vendor/assets/stylesheets/blueprint/src/forms.css",
    "vendor/assets/stylesheets/blueprint/src/grid.css",
    "vendor/assets/stylesheets/blueprint/src/grid.png",
    "vendor/assets/stylesheets/blueprint/src/ie.css",
    "vendor/assets/stylesheets/blueprint/src/print.css",
    "vendor/assets/stylesheets/blueprint/src/reset.css",
    "vendor/assets/stylesheets/blueprint/src/typography.css",
    "vendor/assets/stylesheets/breathe/jquery.tooltip.css",
    "vendor/assets/stylesheets/breathe/navmenu.css",
    "vendor/assets/stylesheets/breathe/print.css",
    "vendor/assets/stylesheets/breathe/puavo.css",
    "vendor/assets/stylesheets/breathe/screen.css",
    "vendor/assets/stylesheets/breathe/topmenu.css",
    "vendor/assets/stylesheets/breathe/userform.css",
    "vendor/assets/stylesheets/gray/jquery.tooltip.css",
    "vendor/assets/stylesheets/gray/navmenu.css",
    "vendor/assets/stylesheets/gray/print.css",
    "vendor/assets/stylesheets/gray/puavo.css",
    "vendor/assets/stylesheets/gray/screen.css",
    "vendor/assets/stylesheets/gray/topmenu.css",
    "vendor/assets/stylesheets/jquery.liveSearch.css",
    "vendor/assets/stylesheets/kilohaili-protofish.css",
    "vendor/assets/stylesheets/kilohaili.css",
    "vendor/assets/stylesheets/navmenu.css",
    "vendor/assets/stylesheets/oivang.css",
    "vendor/assets/stylesheets/scaffold.css",
    "vendor/assets/stylesheets/sun_olive/jquery.tooltip.css",
    "vendor/assets/stylesheets/sun_olive/navmenu.css",
    "vendor/assets/stylesheets/sun_olive/print.css",
    "vendor/assets/stylesheets/sun_olive/puavo.css",
    "vendor/assets/stylesheets/sun_olive/screen.css",
    "vendor/assets/stylesheets/sun_olive/topmenu.css",
    "vendor/assets/stylesheets/tea/kilohaili-protofish.css",
    "vendor/assets/stylesheets/tea/kilohaili.css",
    "vendor/assets/stylesheets/tea/navmenu.css",
    "vendor/assets/stylesheets/tea/print.css",
    "vendor/assets/stylesheets/tea/screen.css",
    "vendor/assets/stylesheets/viola/kilohaili-protofish.css",
    "vendor/assets/stylesheets/viola/kilohaili.css",
    "vendor/assets/stylesheets/viola/navmenu.css",
    "vendor/assets/stylesheets/viola/print.css",
    "vendor/assets/stylesheets/viola/screen.css"
  ]
  s.homepage = %q{https://github.com/opinsys/puavo-themes}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Puavo themes}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

